openapi: '3.0.3'

info:
  title: 'Sample API'
  description: |
    # Features
    - Get reviews
    - Post review
  termsOfService: 'https://tastylog.com/terms'
  contact:
    name: 'Customer Support'
    url: 'https://tastylog.com/support/'
    email: 'support-desk@tastylog.com'
  license:
    name: 'MIT License'
    url: 'https://opensource.org/licenses/MIT'
  version: '1.0.0'

servers:
  - url: 'http://localhost:{port}'
    description: 'Local development'
    variables:
      port:
        enum: ['3000', '8080']
        default: '3000'
  - url: 'https://it1.tastylog.com'
    description: 'Integration Test'
  - url: 'https://stg.tastylog.com'
    description: 'Staging'
  - url: 'https://api.tastylog.com'
    description: 'Production'

tags: []

paths:
  /message:
    get:
      summary: 'Sample API get operation'
      description: 'Sample API get operation'
      responses:
        '200':
          description: 'Success operation'
          content:
            application/json:
              schema:
                type: string
                example: 'Hello World'
  /shops/{shopId}/reviews:
    get:
      summary: 'Get specified shop reviews'
      description: '(description): Get specified shop reviews'
      tags: ['shops']
      deprecated: false
      parameters:
        - name: shopId
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: 'Success operation'

security: []

components:
  schemas:
    SampleInt32:
      type: integer
      format: int32
    SampleDateString:
      type: string
      format: date-time
